name: Run all tests using DuckDNS
on:
  push:
    paths-ignore:
      - '.github/workflows/*'
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-centos7-duckdns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Run test suite on CentOS7 against Staging using DuckDNS
        run: test/run-test.sh centos7-duckdns
  test-ubuntu-duckdns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Run test suite on Ubuntu against Staging using DuckDNS
        run: test/run-test.sh ubuntu-duckdns
